{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-sync.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-sync.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_PASSWORD: {{ required "Set secret.redisPassword or secret.existingSecret" .Values.secret.redisPassword | b64enc | quote }}
{{- end }}
